feat(firestore-stripe-payments): added mobile subscription payments
invertase/stripe-firebase-extensions pull request #410
Opened 2022-08-01 19:31 UTC by dackers86

fixes: https://github.com/stripe/stripe-firebase-extensions/issues/352

2022-08-02 08:19 UTC, jsteele-stripe commented on firestore-stripe-payments/functions/src/index.ts
> +          const paymentIntent = await stripe.paymentIntents.create({
@dackers86 Curious why you've implemented this this way? That's generally not how subscription payments work. The subscription creation will generate a Payment Intent/Setup Intent (depending on whether there's an amount due) on the initial invoice.

2022-08-02 08:35 UTC, dackers86 commented on firestore-stripe-payments/functions/src/index.ts
> +          const paymentIntent = await stripe.paymentIntents.create({
Oh I see. Checking the `latest_invoice ` I misread that as a previous payment_intent that had already been used. Happy to update to use the generated one from the subscription in this case!

2022-08-23 09:54 UTC, jsteele-stripe requested changes

2022-08-23 09:54 UTC, jsteele-stripe commented on firestore-stripe-payments/functions/src/index.ts
> +          await eventChannel?.publish({
@dackers86 Optional chaining operator is redundant here with the additional `if` statement, right?

2022-08-23 09:54 UTC, jsteele-stripe commented on firestore-stripe-payments/functions/src/index.ts
> +            },
@dackers86 Did we consider adapting the API to allow for passing in other subscription creation [parameters](https://stripe.com/docs/api/subscriptions/create)?

2022-08-23 09:54 UTC, jsteele-stripe commented on firestore-stripe-payments/functions/src/index.ts
> +            items: [{ plan: price }],
```suggestion
            items: [{ price }],
```
`plan`, and Plans generally, are deprecated (although backwards compatible).

2022-08-23 09:54 UTC, jsteele-stripe commented on firestore-stripe-payments/functions/src/index.ts
> +            items: [{ plan: price }],
@dackers86 Could we adapt `items` to serialize the `line_items` data from the Firestore document? Their APIs are quite similar.

2022-08-23 09:54 UTC, jsteele-stripe commented on firestore-stripe-payments/functions/src/index.ts
> -            setupIntentClientSecret,
@dackers86 This could still be required for `mode: 'setup'` 'sessions'.

2022-08-23 09:54 UTC, jsteele-stripe commented on firestore-stripe-payments/functions/src/index.ts
> -          throw new Error(
@dackers86 Shall we keep this to handle instances where somebody passes an unknown `mode` value?

2022-08-23 22:19 UTC, dackers86 commented on firestore-stripe-payments/functions/src/index.ts
> -          throw new Error(
Agreed! Error re-added

2022-08-23 22:19 UTC, dackers86 commented on firestore-stripe-payments/functions/src/index.ts
> -            setupIntentClientSecret,
Ok, re-added.

2022-08-23 22:20 UTC, dackers86 commented on firestore-stripe-payments/functions/src/index.ts
> +          await eventChannel?.publish({
You're correct, the if statement will cover this. Removed optional chaining.

2022-08-23 22:27 UTC, dackers86 commented on firestore-stripe-payments/functions/src/index.ts
> +            },
Are there any particular parameters that we would like to include? I'm not sure if I know of any others have been requested, so originally kept the fields to a minimum.

2023-02-27 20:19 UTC, SohelIslamImran commented
Waiting for this PR to merge @dackers86 . [**Here is an example of subscription in mobile implementation**](https://github.com/stripe/stripe-react-native/blob/dafa335ed146e0cb074b04a9d5ef4a8fc1ed7317/example/server/index.ts#L573-L618)

```ts
app.post('/payment-sheet-subscription', async (_, res) => {
  const { secret_key } = getKeys();


  const stripe = new Stripe(secret_key as string, {
    apiVersion: '2020-08-27',
    typescript: true,
  });


  const customers = await stripe.customers.list();


  // Here, we're getting latest customer only for example purposes.
  const customer = customers.data[0];


  if (!customer) {
    return res.send({
      error: 'You have no customer created',
    });
  }


  const ephemeralKey = await stripe.ephemeralKeys.create(
    { customer: customer.id },
    { apiVersion: '2020-08-27' }
  );
  const subscription = await stripe.subscriptions.create({
    customer: customer.id,
    items: [{ price: 'price_1L3hcFLu5o3P18Zp9GDQEnqe' }],
    trial_period_days: 3,
  });


  if (typeof subscription.pending_setup_intent === 'string') {
    const setupIntent = await stripe.setupIntents.retrieve(
      subscription.pending_setup_intent
    );


    return res.json({
      setupIntent: setupIntent.client_secret,
      ephemeralKey: ephemeralKey.secret,
      customer: customer.id,
    });
  } else {
    throw new Error(
      'Expected response type string, but received: ' +
        typeof subscription.pending_setup_intent
    );
  }
});
```

2023-03-01 13:50 UTC, dackers86 commented
Hi @jsteele-stripe.

Are you ok with the feedback? 

I'm happy merge if we can this PR in if needed.

2023-06-12 12:05 UTC, algodextrous commented
please merge the PR

2023-08-30 14:32 UTC, merged